### ISSUE TITLE
[storybook] actions are broken for all stories

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#594]
Noticed in #592, but has likely been present for a while. Stories with actions are all broken - not logged to the action panel and a console error is logged:

```
Uncaught TypeError: toISOString is not a function
    at String.toJSON (<anonymous>)
    at Object.<anonymous> (index.umd.js:1)
    at JSON.stringify (<anonymous>)
    at stringify (index.js:353)
    at PostmsgTransport.send (index.js:148)
    at handler (index.js:126)
    at Channel.emit (index.js:136)
    at actionHandler (action.js:47)
    at Object.ca (react-dom.production.min.js:14)
    at ja (react-dom.production.min.js:15)
```

There is an open issue on the storybook repo without resolution. `https://github.com/storybookjs/storybook/issues/6471` 

We didn't have this issue when we were on storybook v5.0.11.

**Comment by tay1orjones** [comment]
This appears to be fixed by #554. Actions are working in the `storybook-5.2` WIP branch.

**Comment by tay1orjones** [comment]
Update, any time I pull `master` into `storybook-5.2`, the actions break. So there's something in the config/dependencies that causes this to discretely break. I'll continue to look further into this.

**Comment by davidicus** [comment]
this is no longer an issue
